@startuml
Bibliotheque - Utilisateur : Possède
Album -o Bibliotheque : contient 
Editeur -- Collection : est édité par
Collection -- Serie : est composée de
Serie -- Album : est composée de 
Auteur o- Album : est écrit par 
(Album, Auteur) .. AlbumAuteurs
Album -- Commentaire : possède
@enduml
